### PR TITLE
Bump version to 8.2.0

### PR DESCRIPTION
**Pull request by vanitabarrett**
Update related navigation sidebar helper to return mainstream topics alongside whitehall topics

### CODE REVIEW

**Comment by andysellick** [comment]
@vanitabarrett hold fire on this for a sec, we just started a different PR for versioning this... https://github.com/alphagov/govuk_navigation_helpers/pull/108

**Comment by vanitabarrett** [comment]
@andysellick Sure, no worries!

**Comment by andysellick** [comment]
We'll add our changelog stuff into here, one sec.

**Comment by sihugh** [comment]
Thanks @vanitabarrett, I've added a commit with our line.

**Comment by sihugh** [comment]
Thanks @vanitabarrett, I've added a commit with our line.

**Pull request merged**
